name: Node.js CI

on: 
  push:
    branches: ["master"]
  pull-request:
    branches: ["master"]



jobs:
  build:
    runs-on:ubuntu-latest
  strategy:
    matrix:
      node-version: ["20.x","21.x"]
  
  steps:
  - uses: actions/checkout@v3
  - name: Use Node.js ${{matrix.node-version}}
  - uses: actions/setup-node@v3
    with: 
      node-version: S{{matrix.node-version}}
      cache: 'npm'
  - run: npm install
  - run: npm install --save-dev sequelize-cli
  - run: npm run build --if-present
  - run: npm test